### ISSUE TITLE
Typora + Dropbox + MWeb 使用教程

### ISSUE THREAD

**Issue by zhouxincheng** [DeppWang/youdaonote-pull#10]
请仓主有空写下Typora + Dropbox + MWeb的使用教程。
我试着先导出有道云笔记到本地电脑上，再同步到dropbox，iPhone端使用mweb查看dropbox文件不成功。原因是同步的文件需要是由MWeb客户端记录的笔记才可（即需要docs和mainlib.db文件才行），如何才能直接用Typora写，然后手机端查看？

**Comment by DeppWang** [comment]
你 iPhone 下个 Dropbox 就行，MWeb 选择打开 Dropbox 中文件。此种方式需要一直穿墙，看你自己的需求。

也可以用 iCloud 代替 Dropbox，用 Pretext 代替 MWeb。[Work with Mobile and other Devices](https://support.typora.io/Sync/)

**Comment by zhouxincheng** [comment]
iPhone用的就是MWeb+dropbox，但是同步之后文件夹里头的都是空，查了下MWeb说是因为文件夹里头缺少mainlib.db 和 docs文件，所以没有被MWeb识别。有办法解决吗？或者是我的操作方式有误？我原本认为只要是dropbox里头有md文件，就可以被MWeb同步并识别。

**Comment by zhouxincheng** [comment]
MWeb同步问题：
![IMG_2078](https://user-images.githubusercontent.com/15705377/85218637-9acd4480-b3ce-11ea-9867-49c5d4c54e17.PNG)

**Comment by DeppWang** [comment]
我认为 MWeb 就是打开文件的某个目录的文件。可以是本地、iCloud 或 Dropbox。我没有设置你说的这个 mainlib.db 和 docs文件。你应该是哪里操作有问题，我是直接直接添加的 Dropbox 文件夹。

![image](https://user-images.githubusercontent.com/21981221/85218708-59896480-b3cf-11ea-9338-3ead8c71008f.png)

**Comment by zhouxincheng** [comment]
我刚开始想的和你一样 我再折腾下吧 谢谢
