### ISSUE TITLE
安装依赖包一直报错pip install -r requirements.txt

### ISSUE THREAD

**Issue by guyeu9** [DeppWang/youdaonote-pull#101]
File "c:\users\administrator\appdata\local\programs\python\python38\lib\site-packages\pip-23.0.1-py3.8.egg\pip\_internal\utils\encoding.py", line 34, in auto_decode
    return data.decode(
UnicodeDecodeError: 'gbk' codec can't decode byte 0xac in position 54: illegal multibyte sequence

**Comment by DeppWang** [comment]
requirements.txt 文件格式问题，可使用以下格式单独安装包
```
pip install requests==2.22.0 
```

**Comment by guyeu9** [comment]
> requirements.txt 文件格式问题，可使用以下格式单独安装包
> 
> ```
> pip install requests==2.22.0 
> ```

不行，还是一样的报错，始终无法往下进行

**Comment by guyeu9** [comment]
![image](https://user-images.githubusercontent.com/106571082/229019990-123d983e-bd30-4cd5-86bd-299d8106ed23.png)

**Comment by guyeu9** [comment]
我参照chatgpt用了一下改格式为u-8的方法，还是这个报错，不晓得则呢么回事

> requirements.txt 文件格式问题，可使用以下格式单独安装包
> 
> ```
> pip install requests==2.22.0 
> ```

**Comment by guyeu9** [comment]
可行，原来得单独把txt里面的内容复制出来单独安装
