### ISSUE TITLE
md导出无法写入超链接

### ISSUE THREAD

**Issue by tdccj** [DeppWang/youdaonote-pull#107]
md导出后有道云的超链接会变成文字，并且不会显示完整链接
例如：
MCU电源电路及元件选型考虑 - 知乎 (zhihu.com)

**Comment by kamiljune** [comment]
> md导出后有道云的超链接会变成文字，并且不会显示完整链接 例如： MCU电源电路及元件选型考虑 - 知乎 (zhihu.com)

兄dei，你看看 #115 我支持了
