### ISSUE TITLE
图片格式变为“octet-stream”

### ISSUE THREAD

**Issue by chi-bin** [DeppWang/youdaonote-pull#113]
不知道是不是🐕有道更新了啥玩意儿，context-type里头的内容应该是统一变成了octet-stream，原有的写法没有识别出来，可以按照下面的方式取到实在的文件名，不清楚是不是所有的静态资源都有对应的这个属性，希望大佬的master分支可以修复下这个致命问题
临时修复的PR已提：https://github.com/DeppWang/youdaonote-pull/pull/112
![image](https://github.com/DeppWang/youdaonote-pull/assets/44606593/42174b25-7b2b-4360-948d-b29e3e5e7e05)
Ps:感谢 @[kamiljune](https://github.com/kamiljune)的改进建议以兼容Gif格式的图片，最新的改动放在了PR里，大家有需要请自取
![image](https://github.com/DeppWang/youdaonote-pull/assets/44606593/9ceca874-193c-4708-8203-4bd125ee7956)

**Comment by chi-bin** [comment]
注意上面的修复方式，如果有同名的文件会被覆盖，请参考下面的方式加上唯一标识
![image](https://github.com/DeppWang/youdaonote-pull/assets/44606593/6e793225-a91d-4389-a1f9-433b42c581dd)

**Comment by lenvoh** [comment]
未定义“parse”,请问这个function是在哪里定义的

**Comment by chi-bin** [comment]
> 未定义“parse”,请问这个function是在哪里定义的

抱歉，头文件忘记截图了，是从urllib中引入进来的
![image](https://github.com/DeppWang/youdaonote-pull/assets/44606593/ff47161c-58fe-4b99-8322-08b1d9058aab)

**Comment by lenvoh** [comment]
感谢更新，可以使用了

**Comment by Yunmoyan** [comment]
请问有办法可以把octet-stream格式的图片强制改成jpg或者png吗，本地Markdown用obsidian识别不出来

**Comment by kamiljune** [comment]
> 

楼长这个PR就是解决图片问题的撒，拉下来直接用就好

**Comment by Yunmoyan** [comment]
> > 
> 
> 楼长这个PR就是解决图片问题的撒，拉下来直接用就好

啊，谢谢你，才发现我拉下来的是老哥你的pull.py，感谢

**Comment by Yunmoyan** [comment]
感谢，完美离开💢可恶的有道君

**Comment by dbsxdbsx** [comment]
额，我刚刚拉了最新master代码，才发现所有图片变成了octet-stream=_=

**Comment by Yunmoyan** [comment]
> 额，我刚刚拉了最新master代码，才发现所有图片变成了octet-stream=_=

你拉取楼主的pr就可以解决图片问题了

**Comment by dbsxdbsx** [comment]
> > 额，我刚刚拉了最新master代码，才发现所有图片变成了octet-stream=_=
> 
> 你拉取楼主的pr就可以解决图片问题了

感谢， 我已在弄了。
