### ISSUE TITLE
大家是否有遇到过，导出数据不全的问题（修改时间 较早的笔记无法导出）。

### ISSUE THREAD

**Issue by taotao830** [DeppWang/youdaonote-pull#116]
大家是否有遇到过，导出数据不全的问题。

我今天（2023.08.02） 导出了一份 数据， 发现修改时间在2022.01.26 之前的笔记都没有导出来。
于是我检查了一下去年（2022.12.22）导出的数据，修改时间在2021.05.24 之前的笔记都没有导出来。

似乎修改时间过久的笔记都无法导出。

大伙有没有什么想法和建议

**Comment by plutoghost** [comment]
请问改的是哪个位置，我看到好多个地方都有
