### ISSUE TITLE
目前pull下来笔记为json格式

### ISSUE THREAD

**Issue by chunxingque** [DeppWang/youdaonote-pull#119]
pull下来是成功的
```
新增「D:/youdaonote/obsidian/*****************.md」，云笔记原格式为 note
此 note 笔记应该为 17 年以前新建，格式为 html，将转换为 Markdown ...
```
打开后为JSON格式
```
{"2":"1","3":"Ju9C-1621846617594","4":{"version":1,"incompatibleVersion":0,"fv":"0"},"5":[{"3":"3060-1621846615933","5":[{"2":"2","3":"p5PQ-1621846617594"}]},{"3":"8H1C-1680162199017","5":[{"2":"2","3":"ecrv-1680162199015","7":[{"8":"ssl: auth method ssl requires a username"}]}]}],"\_\_compress\_\_":true,"title":""}
```

我猜测有道云笔记新增了JSON的格式

**Comment by JackyWay** [comment]
好像今年的笔记批量倒不出来了，格式都不对，以取旧笔记就没问题。

**Comment by DeppWang** [comment]
我测试新创建的文档格式是有这个问题，修改原来的文档倒没有问题，应该有道云笔记改了文档的存储格式。

大家尽快把原来的笔记导出来吧，我不会再针对新的格式再开发了

**Comment by ganjiayi** [comment]
这应该是笔记格式的问，我印象中，很久之前就有过格式更新，从编辑笔记时显示的工具栏可以看出来。以前创建的和后面新建的笔记，在编辑的时候是有区别的，我对比了一下导出的文件，也确实是这样的，新格式全部都是JSON。

**Comment by chunxingque** [comment]
> 我修改了这个项目，针对JSON格式进行格式进行转换，代码在这里：https://github.com/chunxingque/youdaonote-pull.git

**Comment by chunxingque** [comment]
我修改了这个项目，针对JSON格式进行格式进行转换，代码在这里：https://github.com/chunxingque/youdaonote-pull.git
