### ISSUE TITLE
not enough arguments for format string

### ISSUE THREAD

**Issue by nickyoungforu** [DeppWang/youdaonote-pull#12]
脚本执行一半遇到这个问题：
 RuntimeError Expected object of device type cuda but got device ty.md ，「云笔记原格式为 .note」
not enough arguments for format string

**Comment by DeppWang** [comment]
1. `RuntimeError Expected object of device type cuda but got device ty.md` 就是笔记名吗？前面应该有「新增」两个字吧
2. 贴一下 `RuntimeError Expected object of device type cuda but got device ty.md` 笔记的下一个笔记名

**Comment by nickyoungforu** [comment]
1.抱歉，runtimeerror是我笔记名的一部分，没注意看当成你代码的报错了，完整的信息是 ：
新增 ./export/工作笔记/pytorch的一点坑： RuntimeError Expected object of device type cuda but got device ty.md ，「云笔记原格式为 .note」
not enough arguments for format string
2.下一个笔记名，应该是有道云笔记中按顺序排布的吧？名字是tensorflow fine tuning

**Comment by DeppWang** [comment]
`tensorflow fine tuning` 代码块中含有 `%` 这样的占位符？针对这种情况，我优化了代码，你 pull 最新代码，再执行试试

**Comment by nickyoungforu** [comment]
tensorflow fine tuning 代码块确实中含%。这个问题已经在新代码中已解决。多谢。
