### ISSUE TITLE
Windows下导出，所有的图片都没有导出

### ISSUE THREAD

**Issue by qinshaolin** [DeppWang/youdaonote-pull#121]
环境：
Windows 10 x64
Git 2..42.0.windows.2
Python 3.11.5

requirements包:
Installing collected packages: chardet, Brotli, urllib3, soupsieve, six, idna, certifi, requests, beautifulsoup4, markdownify
Successfully installed Brotli-1.0.9 beautifulsoup4-4.12.2 certifi-2023.7.22 chardet-3.0.4 idna-2.8 markdownify-0.5.1 requests-2.22.0 six-1.16.0 soupsieve-2.5 urllib3-1.25.11

导出结果：
![image](https://github.com/DeppWang/youdaonote-pull/assets/94038835/c2793ba7-f636-47a1-981a-c787a734c7ef)
![image](https://github.com/DeppWang/youdaonote-pull/assets/94038835/35cc6497-d48e-401b-bb8f-41a6bc45c635)
![image](https://github.com/DeppWang/youdaonote-pull/assets/94038835/3a272271-2cc3-48e0-bab9-912d54ab3269)
导出命令输出提示“转换有道云笔记中的有道云图片链接...，请检查文件！错误提示：'download'”
导出笔记所有目录下的images目录中都没有图片文件
打开导出的markdown格式笔记，图片链接是有道云笔记网上的链接，不是本地路径的链接
请问，是Windows有这个问题，还是有道云笔记调整了方式，导致下载不了图片？

**Comment by n0vic30926** [comment]
遇到同样的问题

**Comment by DeppWang** [comment]
可能是有道云笔记资源的问题
