### ISSUE TITLE
导出后格式不对

### ISSUE THREAD

**Issue by yuyongxr** [DeppWang/youdaonote-pull#125]
{"2":"1","3":"Ju9C-1621846617594","4":{"version":1,"incompatibleVersion":0,"fv":"0"},"5":[{"3":"3060-1621846615933","5":[{"2":"2","3":"p5PQ-1621846617594","7":[{"8":"SQL注入是一种常见的Web应用程序攻击方式，攻击者通过在Web应用程序中注入恶意SQL语句，从而获取敏感数据、篡改数据等目的。为了避免SQL注入漏洞，可以采取以下几种措施："}]}]},{"3":"hHA5-1684378943316","4":{"version":1,"li":"3mQW-1684378943332","ll":1,"lt":"ordered"},"5":[{"2":"2","3":"qGWD-1684378943315","7":[{"8":"输入验证（推荐）："},{"8":"对用户输入的数据进行验证和过滤，避免特殊字符和SQL注入语句被注入到SQL查询语句中","9":[{"2":"b"}]},{"8":"。例如，可以使用PHP函数mysqli\_real\_escape\_string()或PDO::quote()来转义输入的数据，避免SQL注入漏洞。"}]}],"6":"l"},{"3":"e5oC-1684378943318","4":{"version":1},"5":[{"2":"2","3":"05Ec-1684378943317"}]},{"3":"8uCn-1684378943320","4":{"version":1,"li":"3mQW-1684378943332","ll":1,"lt":"ordered"},"5":[{"2":"2","3":"DFYs-1684378943319","7":[{"8":"使用预处理语句（推荐）：在使用动态SQL语句时，"},{"8":"建议使用预处理语句，将SQL语句和参数分离","9":[{"2":"b"}]},{"8":"，避免将不可信的数据直接拼接到SQL语句中。例如，可以使用PHP中的PDO或mysqli扩展库的预处理语句功能，对参数进行绑定和执行，在保证安全性的同时提高性能。"}]}],"6":"l"},{"3":"Gxz2-1684378943322","4":{"version":1},"5":[{"2":"2","3":"MAiE-1684378943321"}]},{"3":"uE84-1684378943324","4":{"version":1,"li":"3mQW-1684378943332","ll":1,"lt":"ordered"},"5":[{"2":"2","3":"dfwH-1684378943323","7":[{"8":"使用最小权限原则：在数据库中设置合适的用户权限，避免普通用户拥有管理员权限，从而降低SQL注入的风险。"}]}],"6":"l"},{"3":"ihvb-1684378943327","4":{"version":1},"5":[{"2":"2","3":"mrmU-1684378943325"}]},{"3":"AT8T-1684378943329","4":{"version":1,"li":"3mQW-1684378943332","ll":1,"lt":"ordered"},"5":[{"2":"2","3":"tak3-1684378943328","7":[{"8":"定期更新组件和库文件：定期更新Web应用程序的组件和库文件，修补已知的安全漏洞，提高Web应用程序的安全性。"}]}],"6":"l"},{"3":"lDvs-1684379032466","5":[{"2":"2","3":"Isdg-1684379032465","7":[{"8":"需要注意的是，不同的Web应用程序可能存在不同的安全威胁，开发人员需要针对不同的场景选择相应的防范措施。","9":[{"0":"#24292f","2":"c"},{"0":"Arial","2":"ff"}]}]}]},{"3":"eVs8-1684378943331","4":{"version":1},"5":[{"2":"2","3":"so6M-1684378943330"}]}],"\_\_compress\_\_":true,"title":""}

导出后的文件内容是这样的。
原始文件是这样的：
<img width="849" alt="image" src="https://github.com/DeppWang/youdaonote-pull/assets/31801858/7b315387-2a9f-4bbd-be7e-50f5f9e723df">

**Comment by rxcccc** [comment]
我也是这样的。运行脚本时，窗口上显示“笔记应该为17年以前新建，格式为html，将转换为MarkDown”。Windows10+Python3.11.3。

**Comment by REPUC** [comment]
+1

**Comment by DeppWang** [comment]
此问题已解决
