### ISSUE TITLE
.note文件导出失败：note 笔记转换 MarkDown 失败，将跳过 IndexError('child index out of range')，且会自动退出py窗口，不知道是否执行完成。

### ISSUE THREAD

**Issue by guyeu9** [DeppWang/youdaonote-pull#126]
新增「D:/下载/youdaonote-pull-master (1)/youdaonote-pull-master/youdaonote/来自手机/微信延迟，四个小步骤完美解决!

.note」失败！请检查文件！错误提示：[Errno 22] Invalid argument: 'D:/下载/youdaonote-pull-master (1)/youdaonote-pull-master/youdaonote/来自手机/微信延迟，四个小步骤完美解决!\n\n.note'
note 笔记转换 MarkDown 失败，将跳过 IndexError('child index out of range')

例如这个笔记：https://note.youdao.com/s/a7ut0zN1
就无法导出提示错误，对比发现这些都是纯文字版本的note居多，不知道具体什么问题。

**Comment by DeppWang** [comment]
分享笔记链接已失效，可能是笔记太老的原因
