### ISSUE TITLE
运行失败，提示no such file or directory

### ISSUE THREAD

**Issue by theseventhman** [DeppWang/youdaonote-pull#135]
![运行python脚本失败](https://github.com/DeppWang/youdaonote-pull/assets/17475381/ea28f5f0-e3ef-46d4-84a8-c4c735a5c18b)

**Comment by theseventhman** [comment]
看了下，是创建不了logs文件夹写入不了日志文件，我手动在目录下新建了一个logs文件夹就可以成功运行了

**Comment by DeppWang** [comment]
感谢反馈，已修复
