### ISSUE TITLE
安装依赖Brotli报错

### ISSUE THREAD

**Issue by HBJ008** [DeppWang/youdaonote-pull#136]
安装Brotli依赖的时候报下面的错误
<img width="960" alt="PixPin_2024-05-10_15-59-18" src="https://github.com/DeppWang/youdaonote-pull/assets/89245144/8c674e3b-65ee-44f0-a00d-f9508b33f8db">
我使用的python版本是3.12.3，是因为python版本太新吗？请问怎么解决

**Comment by DeppWang** [comment]
你单独安装 Brotli、不指定版本号试试

**Comment by HBJ008** [comment]
可以安装了，默认给我安装了1.1.0的版本，但是现在启动脚本的时候又会抱下面的错误，ModuleNotFoundError
<img width="558" alt="2" src="https://github.com/DeppWang/youdaonote-pull/assets/89245144/9ab3c0ad-b96c-4183-9ca8-b04c8bee1283">

**Comment by DeppWang** [comment]
第 16 行报错，requests 包安装没有

**Comment by HBJ008** [comment]
安装了2.22.0版本的
![image](https://github.com/DeppWang/youdaonote-pull/assets/89245144/aebae091-e42d-48e8-a5c7-469682c616bd)

**Comment by DeppWang** [comment]
可能是你 Python 版本太新了，你用 pyenv 安装个 Python 3.11.7 试试

**Comment by HBJ008** [comment]
换成Python3.11.7版本后就能正常使用了，问题已经解决，文档也已经导出，谢谢
