### ISSUE TITLE
ModuleNotFoundError: No module named 'urllib3.packages.six.moves'

### ISSUE THREAD

**Issue by sun-jingfeng** [DeppWang/youdaonote-pull#137]
执行python3 pull.py后报错ModuleNotFoundError: No module named 'urllib3.packages.six.moves'。确认urllib3已安装，版本为1.25.11。

**Comment by DeppWang** [comment]
macOS or Windows? Python3 版本是多少？

**Comment by sun-jingfeng** [comment]
> macOS or Windows? Python3 版本是多少？
macOS版本：14.4.1 
Python3版本：3.12.3

**Comment by DeppWang** [comment]
我验证了一下，是 Python 版本的问题，你用 pyenv 安装个 Python 3.11.7 试试

**Comment by sun-jingfeng** [comment]
> 我验证了一下，是 Python 版本的问题，你用 pyenv 安装个 Python 3.11.7 试试

感谢大佬，解决了

**Comment by dongyuwei** [comment]
遇到同样错误，Mac上Python版本是3.12.4，执行 pip3 uninstall urllib3后莫名其妙就好了。

非常好用的软件，非常感谢！
