### ISSUE TITLE
拉取信息的时候出现 错误提示：“content-type”

### ISSUE THREAD

**Issue by xxk101010** [DeppWang/youdaonote-pull#14]
很多文件夹拉取成功，拉取有道云图床图片链接的时候出现 错误提示：“content-type”
![image](https://user-images.githubusercontent.com/35319060/87904332-a2950d00-ca90-11ea-986d-fdbf2ee7942d.png)

**Comment by xxk101010** [comment]
![image](https://user-images.githubusercontent.com/35319060/87905360-fa347800-ca92-11ea-834d-f5e38e4c8782.png)
我的debug了一下，发现接收的reponse有时候不包含 content-Type的key 导致错误

**Comment by DeppWang** [comment]
👍，我下班了优化一下代码，或者你帮忙优化一下，提个 pr
