### ISSUE TITLE
导出后的markdown全部是混乱的

### ISSUE THREAD

**Issue by leonvogle** [DeppWang/youdaonote-pull#141]
比如，我有一篇笔记内容如下，内容很简短，而且是纯文本，但是导出来的markdown就变成这样了，根本不是markdown的格式。

{"2":"1","3":"PZKA-1703764528807","4":{"fv":"0"},"5":[{"3":"5trwg1577615730430","5":[{"2":"2","3":"nrSq-1703764528807","7":[{"8":"轮毂和轮胎需要做记号（轮毂和轮胎直接用粉笔画一笔，做记号。需要知道轮胎和轮毂的相对位置。）安装轮胎时必须按照原来的记号对应上。"}]}]},{"3":"56wymt1577615730565","5":[{"2":"2","3":"cter-1703764528807"}]},{"3":"58uktu1577615665220","5":[{"2":"2","3":"Qsg7-1703764528807","7":[{"8":"原厂的轮胎和轮毂的配重是相对应的，如果补胎时不注意，那么安装后的配重就会改变，在高速或长途驾驶时会出现方向盘抖动，继而发生危险。做记号进行拆卸安装轮胎，则不需要做动平衡，否则需要重新做动平衡进行轮胎轮毂配重。"}]}]}],"\_\_compress\_\_":true}

**Comment by DeppWang** [comment]
请给分享一个有问题文章的链接

**Comment by leonvogle** [comment]
> 请给分享一个有问题文章的链接

大部分文章都是这样的，我现在分享一个
【有道云笔记】火花塞更换时间 https://note.youdao.com/s/RikTNbI8

**Comment by DeppWang** [comment]
你是什么系统，我 macOS 测试下载没有问题

**Comment by leonvogle** [comment]
> 你是什么系统，我 macOS 测试下载没有问题

Win10系统，会不会跟Python版本有关系？

**Comment by DeppWang** [comment]
你安装 Python 3.11.7 后再 pull 试试（可使用 pyenv）

**Comment by leonvogle** [comment]
> 你安装 Python 3.11.7 后再 pull 试试（可使用 pyenv）

下次再试试看

**Comment by leonvogle** [comment]
> 你安装 Python 3.11.7 后再 pull 试试（可使用 pyenv）

更新了Python，正常了。
