### ISSUE TITLE
笔记内容，导出不全！

### ISSUE THREAD

**Issue by HACK-WU** [DeppWang/youdaonote-pull#143]
![image-20240604143428095](https://hackwu-images-1305994922.cos.ap-nanjing.myqcloud.com/images/image-20240604143428095.png)

如图，笔记中顶部灰色框的内容没有导出来。

**Comment by DeppWang** [comment]
请分享一个有问题的有道云笔记文件链接

**Comment by HACK-WU** [comment]
【有道云笔记】有道云笔记
https://note.youdao.com/s/6hyEIgfU

以上是有问题的笔记内容

**Comment by DeppWang** [comment]
那个现在的格式是怎么样的？没有对比。

**Comment by HACK-WU** [comment]
我测试了一下，发现虽然现实了高亮框的内容显示，但是出现了内容导出错误的情况，以下是错误的导出：



![image-20240612173316238](https://hackwu-images-1305994922.cos.ap-nanjing.myqcloud.com/images/image-20240612173316238.png)





然后我看了源码，加上了一行代码以后，显示正常：

![image-20240612180722042](https://hackwu-images-1305994922.cos.ap-nanjing.myqcloud.com/images/image-20240612180722042.png)



正常的效果如下：

![image-20240612180237127](https://hackwu-images-1305994922.cos.ap-nanjing.myqcloud.com/images/image-20240612180237127.png)

**Comment by DeppWang** [comment]
你是 Windows 电脑？

**Comment by DeppWang** [comment]
奇怪了，我这边没有这个问题。你截图一下你错误的 Markdown 源文件看看

**Comment by HACK-WU** [comment]
* 第一个错误案列

![image-20240612182604122](https://hackwu-images-1305994922.cos.ap-nanjing.myqcloud.com/images/image-20240612182604122.png)





* 第二个错误案列
* 原文链接：https://note.youdao.com/s/95GhZMJz

![image-20240612182623372](https://hackwu-images-1305994922.cos.ap-nanjing.myqcloud.com/images/image-20240612182623372.png)

**Comment by HACK-WU** [comment]
一个建议，代码框改成引用，感觉会更好。
同时刚才引发的问题，也消失了。

![image-20240612185539018](https://hackwu-images-1305994922.cos.ap-nanjing.myqcloud.com/images/image-20240612185539018.png)



![image-20240612185606747](https://hackwu-images-1305994922.cos.ap-nanjing.myqcloud.com/images/image-20240612185606747.png)

**Comment by DeppWang** [comment]
我使用其它方式解决了这个问题。还是使用的代码块

**Comment by HACK-WU** [comment]
![image-20240612191650868](https://hackwu-images-1305994922.cos.ap-nanjing.myqcloud.com/images/image-20240612191650868.png)



其实呢，高亮块里面还可以有其他的markdown格式的内容，所以如果高亮使用代码块代替的话，就不能显示其他的格式了，

但是引用就可以。 如果以后想支持这样的显示的话，引用或许不错。



这是引用中的内容：

> ```python
> python
> ```
>
> * 123445
>
> # 标题

**Comment by DeppWang** [comment]
确实有这个问题。如何高亮块有其它格式，使用引用也还需要额外处理，后面遇到这种情况再优化
