### ISSUE TITLE
ydnote_dir配置问题

### ISSUE THREAD

**Issue by debugbb** [DeppWang/youdaonote-pull#149]
操作系统版本：如 macOS 12.6
我使用的是release版本，请问ydnote_dir的配置问题，我想导出某个目录下的笔记，按照根目录/子目录的方式配置，会提示指定指定顶层目录不存在，但是如果只留根目录是可以导出的，我想分批导出，请问子目录的应该如何配置？谢谢
![QQ_1721628600403](https://github.com/user-attachments/assets/b3cfe826-0083-4372-afd5-acffb5987788)

**Comment by DeppWang** [comment]
子目录不支持的，只能导出跟目录，可以先导出根目录，再将子目录复制出来

**Comment by debugbb** [comment]
嗯，原来如此
