### ISSUE TITLE
原来格式为表格（table），转换较复杂，未转换，需要手动复制一下

### ISSUE THREAD

**Issue by zhangchenxi0016** [DeppWang/youdaonote-pull#16]
咋复制一下能被markdown正确渲染呢？有没有什么解决方案

**Comment by DeppWang** [comment]
你如果用 [Typora](https://typora.io)，直接在有道云笔记复制表格，在 Typora 里粘贴即可。因为复制的时候带有格式，Typora 能正确渲染。

**Comment by zhangchenxi0016** [comment]
我之前用的vscode 只能复制过去文本 ，换成Typora之后问题解决 谢谢

**Comment by DeppWang** [comment]
不谢，😁
