### ISSUE TITLE
部分笔记转换失败

### ISSUE THREAD

**Issue by tongjun741** [DeppWang/youdaonote-pull#18]
![1597234319808](https://user-images.githubusercontent.com/6827111/90013568-17e2af00-dcd8-11ea-9934-3cad25e2b5ab.jpg)

**Comment by tongjun741** [comment]
错误信息：
mismatched tag: line 1, column 308

note格式的内容：
`<div><span style='color: rgb(68, 68, 68); line-height: 1.5; font-family: "Monaco","Consolas","Lucida Console","Courier New","serif"; font-size: 12px; background-color: rgb(247, 247, 247);'><a href="http://bbs.pcbeta.com/viewthread-1095891-1-1.html">http://bbs.pcbeta.com/viewthread-1095891-1-1.html</a><br></span></div><span style='color: rgb(68, 68, 68); line-height: 1.5; font-family: "Monaco","Consolas","Lucida Console","Courier New","serif"; font-size: 12px; background-color: rgb(247, 247, 247);'><div><span style='color: rgb(68, 68, 68); line-height: 1.5; font-family: "Monaco","Consolas","Lucida Console","Courier New","serif"; font-size: 12px; background-color: rgb(247, 247, 247);'><br></span></div>sudo perl -pi -e 's|\x75\x30\x89\xd8|\xeb\x30\x89\xd8|' /System/Library/Extensions/AppleRTC.kext/Contents/MacOS/AppleRTC</span>`

**Comment by DeppWang** [comment]
这个 note 文件本身就包含 `<div><span style='color: rgb(68, 68, 68); **` 这些内容吗？

**Comment by tongjun741** [comment]
完整的场景是这样的：
1、我使用pull.py导出笔记时发现一条笔记转换失败；
2、登录web端找到这一条笔记，提示“正在对旧版笔记做格式转化！”：
![image](https://user-images.githubusercontent.com/6827111/90088650-050cc080-dd52-11ea-80ba-68a439e1b096.png)
抓包发现浏览器在【1】处请求了一个转化的接口，返回的是html内容，然后在【2】处把这个html传回给服务器：
![image](https://user-images.githubusercontent.com/6827111/90088823-7ba9be00-dd52-11ea-851a-9bdc10d4ec0c.png)
3、再次执行pull.py时这一条笔记就正常了。

**Comment by DeppWang** [comment]
我觉得可能是这样，我看你这条笔记是 16 年的，那时候有道云笔记存放「笔记」应该是使用的 html 格式，而现在使用 xml 格式，我这个脚本默认笔记是 xml 格式，所以执行时会出错。你现在打开这条笔记时，它会将其转换为 xml 格式（格式转化），所以再次执行就没问题了。

**Comment by tongjun741** [comment]
对，只有部分很旧的笔记有这个问题。
你有解决办法吗？不然只能一条条去点了

**Comment by DeppWang** [comment]
像这种旧笔记，第一次下载应该都没成功，此时应该就跟手动点的效果一样吧，再次执行一次 pull.py，应该就可以下载了吧

**Comment by DeppWang** [comment]
我想错了，应该还需要脚本执行一下你这个【2】处的 URL，你看看 2 处 post 请求参数是不是只有 html，帮忙截图一下，我优化一下脚本

**Comment by tongjun741** [comment]
不知道这些够不够：
![image](https://user-images.githubusercontent.com/6827111/90097293-28db0100-dd68-11ea-90da-266c277cb567.png)

**Comment by DeppWang** [comment]
我看调用

**Comment by DeppWang** [comment]
目前没有很好的方法将 html 转换为 Markdown，推荐你用 Typora，它支持 html，这样 html 格式不转换也行。
