### ISSUE TITLE
笔记较多时同步到一半会退出

### ISSUE THREAD

**Issue by tongjun741** [DeppWang/youdaonote-pull#19]
![image](https://user-images.githubusercontent.com/6827111/90013623-347ee700-dcd8-11ea-8f50-212d1cf12163.png)

经调试发现可能是这里的url一直在增加lastId，旧的lastId没删除，导致url过长：
![image](https://user-images.githubusercontent.com/6827111/90013686-57110000-dcd8-11ea-829a-7bb21a43ef2a.png)

**Comment by DeppWang** [comment]
你好，感谢指出，我已经修复了此问题，请 pull 最新代码
