### ISSUE TITLE
能否导将Note转成HTML格式

### ISSUE THREAD

**Issue by lqdflying** [DeppWang/youdaonote-pull#2]
能否导将Note转成HTML格式,方便二次处理,比如静态web或者是导入到Evernote
有道越来越恶心,关掉了导出通用格式的接口,说白了就是怕用户跑了,客观现实就是我笔记太多了,还真的不好跑

**Comment by DeppWang** [comment]
直接转成 Markdown 更好吧，html 不通用，我有时间改成都导出为 Markdown

**Comment by gaosunhao** [comment]
手动复制粘贴到markdown吗？

**Comment by lqdflying** [comment]
> 直接转成 Markdown 更好吧，html 不通用，我有时间改成都导出为 Markdown

能将Node转成MarkDown也行,图片是个大问题,不能丢了图片呀

**Comment by DeppWang** [comment]
@lqdflying 图片应该可以用代码下载下来，我试试

**Comment by DeppWang** [comment]
@gaosunhao 对！

**Comment by DeppWang** [comment]
已实现此功能！

**Comment by lqdflying** [comment]
能否简单的写个README或者加个参数控制,比如--output html[default md]之类的

**Comment by DeppWang** [comment]
output html?

**Comment by lqdflying** [comment]
嗯

**Comment by DeppWang** [comment]
@lqdflying 如果你想转换为 html，用 mdnice.com

**Comment by lqdflying** [comment]
其实不难,我有空写一个
