### ISSUE TITLE
感谢分享

### ISSUE THREAD

**Issue by Jtiag** [DeppWang/youdaonote-pull#20]
可以增加一个修改修改图片 地址为自定义的图床

**Comment by DeppWang** [comment]
macOS 可以利用 [iPic Mover](https://apps.apple.com/us/app/ipic-mover/id1183822957?mt=12) 实现。

**Comment by 6r6** [comment]
太顶了，很好用。不过我这边太多 `.note` 格式老笔记了。300M的笔记只导出了30M，是个遗憾，看来还是要冲一次会员。

**Comment by DeppWang** [comment]
@6r6  2017 年以前的 `.note` 格式没导出成功？
