### ISSUE TITLE
【求助】请检查账号密码是否正确！……

### ISSUE THREAD

**Issue by Lever-888** [DeppWang/youdaonote-pull#21]
非常有用的工具！

作者您好，我按说明运行，总是如下报错提示。用的Mac系统，config文件是按说明里的例子填的。我换用自己的账号也是一样的错误。通过VPN更换了ip也不行。请问有可能是什么原因吗？

{
    "username": "deppwang@163.com",
    "password": "12345678",
    "local_dir": "",
    "ydnote_dir": "",
    "smms_secret_token": ""
}
错误提示：请检查账号密码是否正确！也可能因操作频繁导致需要验证码，请切换网络（改变 ip）或等待一段时间后重试！
已终止执行

**Comment by DeppWang** [comment]
你 config.json 配置后保存了吗？

**Comment by Lever-888** [comment]
> 你 config.json 配置后保存了吗？

感谢您的快速回复，我又试了几次，好像又可以下载了。看来是服务器方面的问题

**Comment by DeppWang** [comment]
好的，可以用就好

**Comment by Lever-888** [comment]
另外，对于17年前的老笔记是不是不完全支持？提示转换失败

「/Users/Lever/Downloads/youdaonote-pull/docs/老笔记留档/工作流水账/2014_12_15.note」转换为 Markdown 失败！请检查文件！
错误提示：[Errno 2] No such file or directory: '/Users/Lever/Downloads/youdaonote-pull/docs/老笔记留档/工作流水账/2014_12_15.note'
此 note 笔记应该为 17 年以前新建，格式为 html，将转换为 Markdown

**Comment by DeppWang** [comment]
原来也有位用户遇到这类问题，当时优化了一下，默认会转换为 Markdown，可能有的场景没测试到。

两个问题：
1. 运行中断了吗
2. 如果文件可以公开的话，帮忙提供一下 2014**.note 这个文件的内容，应该是 HTML 格式，最好直接贴附件。我这边复现一下

**Comment by Lever-888** [comment]
> 原来也有位用户遇到这类问题，当时优化了一下，默认会转换为 Markdown，可能有的场景没测试到。
> 
> 两个问题：
> 
> 1. 运行中断了吗
> 2. 如果文件可以公开的话，帮忙提供一下 2014**.note 这个文件的内容，应该是 HTML 格式，最好直接贴附件。我这边复现一下

- 运行没有中断，只是那一条报错了
- 我没有找到Mac下的.note的文件存在哪里。 不过我发现在有道云中打开那个笔记时，他会自动提示将旧版笔记转换为新版。我把那些出错的都打开，让他转为新版，再用你的程序就可以正常下载转换了。

**Comment by DeppWang** [comment]
这样也是一种解决方式 👍🏻
