### ISSUE TITLE
文件夹里的笔记超过30条就只下载最新的30条

### ISSUE THREAD

**Issue by nnkn** [DeppWang/youdaonote-pull#22]
请问大佬这该如何解决呢？

**Comment by DeppWang** [comment]
这个问题还没遇见过，我晚上看看

**Comment by nnkn** [comment]
解决了，我自己瞎改，“DIR_MES_URL = ”那行的“len=30”我改成了“len=50”就可以了。

**Comment by DeppWang** [comment]
厉害，我到时候改一下源码

**Comment by deagon** [comment]
我现在只下载了 50 条，哈哈

**Comment by DeppWang** [comment]
> 我现在只下载了 50 条，哈哈

改成了 200，pull 一下最新代码，直接改 pull.py 也行，DIR_MES_URL 的 50 改为 100
