### ISSUE TITLE
感谢分享，请问可以直接导出为word么？~

### ISSUE THREAD

**Issue by DesistDaydream** [DeppWang/youdaonote-pull#23]

**Comment by DeppWang** [comment]
看这个：https://github.com/wesley2012/YoudaoNoteExport

**Comment by DesistDaydream** [comment]
> 看这个：https://github.com/wesley2012/YoudaoNoteExport

非常感谢~他那个导出后文件名还是 ID~~我试试改一下你这个。。。光把 URL 改成 doc 的接口还不行。。。
