### ISSUE TITLE
导出的笔记插图后缀名多了个分号";"

### ISSUE THREAD

**Issue by shyer886** [DeppWang/youdaonote-pull#31]
分隔符忘记处理了;
![image](https://user-images.githubusercontent.com/30382446/100577946-3ec30080-331c-11eb-918f-20567906f03a.png)
![image](https://user-images.githubusercontent.com/30382446/100578041-6c0fae80-331c-11eb-8452-826c1fc8caf7.png)
![image](https://user-images.githubusercontent.com/30382446/100578281-e5a79c80-331c-11eb-9198-d8465fd476d9.png)

**Comment by DeppWang** [comment]
后面处理一下，你也可以改一下代码，提交一个 merge。

**Comment by DeppWang** [comment]
已处理， config 配置换一个本地文件夹，重新运行最新的代码
