### ISSUE TITLE
微信扫码登录的还有救吗？

### ISSUE THREAD

**Issue by ManfredHu** [DeppWang/youdaonote-pull#32]
RT

**Comment by DeppWang** [comment]
没救了 😁。这跟这个脚本的原理有关。说到底，这个脚本能实现下载，是利用了 Cookie。 脚本通过账号密码来获取 Cookie，而像第三方的 QQ、微信登录，脚本是无法获取到 Cookie 的。所以没救了。

**Comment by Silypie** [comment]
可以新注册一个账号，将原先的笔记分享至新注册的账号，就可以使用这个脚本了

**Comment by maybe-why-not** [comment]
不能自己登录完把cookie复制出来用吗？

**Comment by DeppWang** [comment]
可以试试。在 `config.json` 的同级目录，新建一个 `cookies.json` 文件（注意 json 是后缀），`cookies.json` 的格式如下：
```json
{
    "cookies": [
        [
            "YNOTE_CSTK",
            "**",
            ".note.youdao.com",
            "/"
        ],
        [
            "YNOTE_LOGIN",
            "**",
            ".note.youdao.com",
            "/"
        ],
        [
            "YNOTE_PERS",
            "**",
            ".note.youdao.com",
            "/"
        ],
        [
            "YNOTE_SESS",
            "**",
            ".note.youdao.com",
            "/"
        ],
        [
            "JSESSIONID",
            "**",
            "note.youdao.com",
            "/"
        ],
        [
            "OUTFOX_SEARCH_USER_ID",
            "**",
            "note.youdao.com",
            "/auth"
        ],
        [
            "OUTFOX_SEARCH_USER_ID",
            "**",
            "note.youdao.com",
            "/login/acc/pe"
        ],
        [
            "YNOTE_URS_VERIFY",
            "**",
            "note.youdao.com",
            "/login/acc/urs/verify"
        ]
    ]
}
```

根据 `YNOTE_URS_VERIFY` 这样的名称找到对应的值，将 `**` 替换成你的。

**Comment by maybe-why-not** [comment]
可以了可以了。全世界有道云笔记第三方登录者，联合起来！

**Comment by hewking** [comment]
稍微改动下可以了，非常感谢

**Comment by ManfredHu** [comment]
我也可以了，感谢

**Comment by AnsonZnl** [comment]
找不到YNOTE_URS_VERIFY字段怎么办....？ @DeppWang

**Comment by DeppWang** [comment]
> 找不到YNOTE_URS_VERIFY字段怎么办....？ @DeppWang

试试不要行不行

应该是有的，刷新页面，找到「主」请求，再找找 cookie

**Comment by AnsonZnl** [comment]
> > 找不到YNOTE_URS_VERIFY字段怎么办....？ @DeppWang
> 
> 试试不要行不行
> 
> 应该是有的，刷新页面，找到「主」请求，再找找 cookie

![image](https://user-images.githubusercontent.com/29278068/104399791-55e84580-558c-11eb-9d46-0ebb4f7a8ba9.png)
刷新了 确实是没有...

**Comment by AnsonZnl** [comment]
> > > 找不到YNOTE_URS_VERIFY字段怎么办....？ @DeppWang
> > 
> > 
> > 试试不要行不行
> > 应该是有的，刷新页面，找到「主」请求，再找找 cookie
> 
> ![image](https://user-images.githubusercontent.com/29278068/104399791-55e84580-558c-11eb-9d46-0ebb4f7a8ba9.png)
> 刷新了 确实是没有...

![image](https://user-images.githubusercontent.com/29278068/104399856-787a5e80-558c-11eb-938a-dfd890774328.png)
不要的话就报错了..

**Comment by DeppWang** [comment]
你是用的什么工具获取的 Cookie？可以用 Chrome 的 DevTools(F12) 获取 Cookie，Network 下找「主」请求（一般是第一个），再找 Cookie

**Comment by AnsonZnl** [comment]
> 你是用的什么工具获取的 Cookie？可以用 Chrome 的 DevTools(F12) 获取 Cookie，Network 下找「主」请求（一般是第一个），再找 Cookie @AnsonZnl

我的也是Chrome...，查看了第一个请求，
![image](https://user-images.githubusercontent.com/29278068/104401075-6dc0c900-558e-11eb-9212-e0e92253e207.png)
还是找不到YNOTE_URS_VERIFY字段
![image](https://user-images.githubusercontent.com/29278068/104401122-85984d00-558e-11eb-8567-c457e13b5036.png)
我试试导出文件然后导入到其他账号可以不，
还有一个问题就是如果自己添加cookies文件，能不能就不需要强制输入账号和密码了，，因为微信登录用户没有就没有显式的账号和密码....

**Comment by AnsonZnl** [comment]
> 你是用的什么工具获取的 Cookie？可以用 Chrome 的 DevTools(F12) 获取 Cookie，Network 下找「主」请求（一般是第一个），再找 Cookie @AnsonZnl
感谢大佬，找到解决办法了并提了一个issue：https://github.com/DeppWang/youdaonote-pull/issues/36

**Comment by damuzhi** [comment]
> > 你是用的什么工具获取的 Cookie？可以用 Chrome 的 DevTools(F12) 获取 Cookie，Network 下找「主」请求（一般是第一个），再找 Cookie @AnsonZnl
> > 感谢大佬，找到解决办法了并提了一个issue：#36
删除config.json中这段
        [
            "YNOTE_URS_VERIFY",
            "**",
            "note.youdao.com",
            "/login/acc/urs/verify"
        ]

**Comment by damuzhi** [comment]
@AnsonZnl 删除这一段就好了
        [
            "YNOTE_URS_VERIFY",
            "**",
            "note.youdao.com",
            "/login/acc/urs/verify"
        ]

**Comment by stern-hcg** [comment]
`{
    "cookies": [
        [
            "YNOTE_CSTK",
            "**",
            ".note.youdao.com",
            "/"
        ],
        [
            "YNOTE_LOGIN",
            "**",
            ".note.youdao.com",
            "/"
        ],
        [
            "S_INFO",
            "**",
            ".note.youdao.com",
            "/"
        ],
        [
            "P_INFO",
            "**",
            ".note.youdao.com",
            "/"
        ],
        [
            "YNOTE_SESS",
            "**",
            ".note.youdao.com",
            "/"
        ],
        [
            "JSESSIONID",
            "**",
            "note.youdao.com",
            "/"
        ],
        [
            "OUTFOX_SEARCH_USER_ID",
            "**",
            "note.youdao.com",
            "/"
        ]

    ]
}
`
有道云笔记网页版登录，cookie信息好像有变更。只需要相应的调整 cookies.json 中对应的键值对就可以了。亲测手机号/验证码登录，上述配置可以成功下载导出。

希望有帮助到有需要的小伙伴们～

**Comment by hzysvilla** [comment]
好像最新的cookie又改版了，s_info和p_info都不见了

**Comment by zoukai3412085** [comment]
亲测可用的解决办法如下：
1. Windows下安装官网的xp版本，可以一键导出有道云格式的ynt格式文件，是包含整个库的单个文件；
2. 再重新用邮箱和密码注册一个账户，将上述ynt文件导入到新的账户中；
3. 然后利用新的账户信息备份和下载
