### ISSUE TITLE
child index out of range

### ISSUE THREAD

**Issue by leozvc** [DeppWang/youdaonote-pull#33]
「/Users/xxxx.note」转换为 Markdown 失败！请检查文件！
错误提示：child index out of range

转换md报错

**Comment by DeppWang** [comment]
明天我看看

**Comment by DeppWang** [comment]
这两天工作实在太忙，周末有时间再处理一下

**Comment by leozvc** [comment]
> 这两天工作实在太忙，周末有时间再处理一下

辛苦了 感觉很多是html的那种旧格式 才会导致这个错误

**Comment by DeppWang** [comment]
有可能是的，你可以多运行几次看看是不是都是这个错。也在有道云笔记上打开一些文件（可以更改一下文件格式），再运行脚本
