### ISSUE TITLE
有道云笔记修改了接口地址，此脚本暂时不能使用！请提 issue'

### ISSUE THREAD

**Issue by wu-junxuan** [DeppWang/youdaonote-pull#34]
请问如何解决

**Comment by DeppWang** [comment]
先多运行几次，如果一直是这个错误的话，可能是有道云笔记修改了接口，处理应该比较费时一点，现在工作比较忙，周末我看一下

**Comment by DeppWang** [comment]
我测试了一下，有道云笔记的接口没有问题。你可能是 config.json 设置得有点不对，或可能账户很久没有使用导致数据格式有点问题

**Comment by wu-junxuan** [comment]
应该是，今早测试通过了。十分感谢！
