### ISSUE TITLE
为什么有的文档下载后只有名字，没有文件后缀，打开也是类似html的内容

### ISSUE THREAD

**Issue by BigYoungs** [DeppWang/youdaonote-pull#35]
RT

**Comment by DeppWang** [comment]
笔记应该为 17 年以前新建，格式为 html，脚本在转换为 markdown 时应该是失败了。解决方法办法把这些笔记在有道云笔记重新点一下，这样有道云笔记就能重新格式化一下数据，再运行一下脚本就好了
