### ISSUE TITLE
有道云微信用户导出（亲测可行）

### ISSUE THREAD

**Issue by AnsonZnl** [DeppWang/youdaonote-pull#36]
- 微信账号称为账号A。
- 然后你得先注册一个有道云笔记账号，要使用**邮箱注册**（因为这样才有账号和密码），下面称为账号B。
- 然后使用账号B登录有道云笔记web端，然后点击**账号设置->账号信息->导入->导入微信笔记**
![输入图片说明](https://images.gitee.com/uploads/images/2021/0113/113857_bc17c51f_1643105.png "屏幕截图.png")
- 一定要点击选择导入**微信账户数据**，之后使用账号A的微信扫码验证就可以了。
- 然后等会数据同步到账号B了，在使用脚本拉取账号B就行了。
![输入图片说明](https://images.gitee.com/uploads/images/2021/0113/113831_a58f0eef_1643105.png "屏幕截图.png")

**Comment by globalblocklist** [comment]
救世主啊

**Comment by bolabola** [comment]
救世主
