### ISSUE TITLE
大佬 看一下

### ISSUE THREAD

**Issue by liujianqiqu** [DeppWang/youdaonote-pull#4]
我分别在git环境和python环境下输入了pullAll那句话，都报错了呢，帮忙看一下吧

![微信图片_20200604190041](https://user-images.githubusercontent.com/50283344/83749068-b679e080-a695-11ea-8d49-dd85628e97bf.png)
![微信图片_20200604190046](https://user-images.githubusercontent.com/50283344/83749069-b7ab0d80-a695-11ea-8710-17573d0969fd.png)

**Comment by DeppWang** [comment]
![image](https://user-images.githubusercontent.com/21981221/83753876-a6fe9580-a69d-11ea-9197-614776028efc.png)

我更新了 README 文件，Windows 电脑先运行这个命令： `pip install requests`

**Comment by liujianqiqu** [comment]
好了 ，安装了这个依赖之后就可以全下下来了，谢谢大佬，我的问题已经解决了。可是出现你之前提到的一个问题，note文件打开之后是一个xml，你看看这个有什么好办法再优化一下吧，谢谢 谢谢

**Comment by DeppWang** [comment]
正在优化。。

**Comment by DeppWang** [comment]
现在实现了将 xml 转换为 Markdown 的功能。
