### ISSUE TITLE
保存到本地的笔记中的图片路径错误

### ISSUE THREAD

**Issue by BugKun** [DeppWang/youdaonote-pull#41]
保存到本地的笔记初根目录的外，其余所有目录下的笔记中的图片路径都缺少了一个层级，导致图片无法显示。
如：markdown中写的是
```markdown
![](./youdaonote-images/XXXXXXXXX.png)
```
而实际的路径应该是`../youdaonote-images/XXXXXXXXX.png`

**Comment by DeppWang** [comment]
你电脑是 Windows 还是 macOS 呢？我自己 macOS 测试是没有这个问题的

**Comment by BugKun** [comment]
Windows 
另外我自己改好了，你那边实现的逻辑有点复杂，我改得简单一点
https://github.com/DeppWang/youdaonote-pull/pull/43

**Comment by DeppWang** [comment]
👍，看到了
