### ISSUE TITLE
网页转存文件导出后显示为未知文件

### ISSUE THREAD

**Issue by amwihgu** [DeppWang/youdaonote-pull#42]
首先导出顺利，感谢脚本。
但是发现仍有一种类型的笔记导出结果为不带扩展名的文件，比如下方这则来自微信公众号的笔记：
http://note.youdao.com/noteshare?id=1041bc6f2596ca150b57edccc971d142&sub=96F960F7AF674D24BE8C6523E3051851
其实就是一则平白的图文公众号，导出后变成一个所附近压缩文件中的那个未知文件。
类似的笔记我还有很多。
不知道是否有一个原因在背后，感谢 ！

[CmK, Cp 和CpK的计算方法.zip](https://github.com/DeppWang/youdaonote-pull/files/6248591/CmK.Cp.CpK.zip)

**Comment by DeppWang** [comment]
我将你分享的笔记保存到我的有道云笔记后，测试下载，没有发现问题。

我尝试保存微信公众号的文章到有道云笔记，测试下载了一下，也没有遇到你所说的这种问题。

由于脚本导出只支持 note 和 md 类型。我猜测可能是你的「来自微信公众号的笔记」不是 note 类型，可以确认一下笔记左上角是否含有以下图标：

![image](https://user-images.githubusercontent.com/21981221/121905570-e0f88200-cd5c-11eb-9210-bc8fb2dc0ea9.png)

可以尝试的解决方案：将几个有问题的笔记在有道云笔记中点击一下，这样可能引起格式的变化，最后重新用脚本下载到新目录对比一下

**Comment by BugKun** [comment]
https://github.com/DeppWang/youdaonote-pull/blob/aeecd847554c7e730a8e7de2fd1a9dd006c246e0/pull.py#L386

我的解决办法是，修改这里的代码，把
```python
if youdao_file_suffix == '.note':
```
改成
```python
if youdao_file_suffix != '.md':
```

**Comment by DeppWang** [comment]
👍，好办法
