### ISSUE TITLE
运行错误

### ISSUE THREAD

**Issue by seramat** [DeppWang/youdaonote-pull#5]
请问，Win10，运行之后出这个是什么原因呢？谢谢
$ python pull.py
▒▒▒▒ config.json ▒▒ʽ▒Ƿ▒▒▒ȷ▒▒
▒▒▒˳▒

**Comment by DeppWang** [comment]
应该是 Windows 系统跟 Unix 哪里有点不一样，我看看

**Comment by DeppWang** [comment]
你使用 PowerShell 命令行运行脚本，你这个是提示：
```
请检查 config.json 格式是否正确！
已退出
```
默认命令行软件应该是中文乱码了
