### ISSUE TITLE
导出时的几个问题

### ISSUE THREAD

**Issue by liues1992** [DeppWang/youdaonote-pull#52]
感谢开发者，整体上很好用。
两个小问题。
1. 有的笔记没有文件后缀，但是是xml格式的
2. 有的文件是note后缀，但是其实里面是纯html

**Comment by M0cK1nG-b1Rd** [comment]
hi 我也碰到了第二个问题。补充截图如下，部分文件没有后缀，然后打开是没有转换的xml代码

<br>
<br>

部分没转换的文件：
<br>

![Snipaste_2021-09-27_23-58-10](https://gitee.com/h1nt_only/figure-bed/raw/master/2021/09/img/testtest.assets/Snipaste_2021-09-27_23-58-10.png)


打开后显示为未转换的xml：


<br>

![Snipaste_2021-09-27_23-58-30](https://gitee.com/h1nt_only/figure-bed/raw/master/2021/09/img/testtest.assets/Snipaste_2021-09-27_23-58-30.png)

<br>

然后经测试linux也会存在同样的问题，生成的没转换的文件都是一样的

**Comment by M0cK1nG-b1Rd** [comment]
今天早上调试了一下，发现是有道下下来的文件中有些虽然内容是note，但是文件本身并没有任何后缀，因而无法进行转换。
<br>
稍晚试着提交一个PR，我的想法是在全部文件下下来后对文件夹做一次遍历，如果文件以<?xml打头又没有后缀的话再次调用转换函数。

**Comment by Newdea** [comment]
@DeppWang 感谢大佬，问题1，我也遇到了，是在windows上，可能是因为笔记比较早，实际是note格式的xml内容。

**Comment by DeppWang** [comment]
此问题已修复
