### ISSUE TITLE
如何才能让图片放到md里面呢？

### ISSUE THREAD

**Issue by YMingF** [DeppWang/youdaonote-pull#59]
现在的导出是将图片统一放到youdao-images这个文件夹里，然后md里面引用本地链接。不过这样就导致文件过大时，迁移笔记很容易失败。
请问有没有办法能够让图片直接下载到md和文字在一起。这样我就可以分批导入文件，既不用担心没文字，也不用担心文件过大迁移失败了。

**Comment by YMingF** [comment]
图床的上传有限制，一小时100张，剩下的就只能到本地了，效率挺低的

**Comment by YMingF** [comment]
> 人家不是给了图床的方式了嘛？ 用图床就好了。

害

**Comment by DeppWang** [comment]
> 现在的导出是将图片统一放到youdao-images这个文件夹里，然后md里面引用本地链接。不过这样就导致文件过大时，迁移笔记很容易失败。 请问有没有办法能够让图片直接下载到md和文字在一起。这样我就可以分批导入文件，既不用担心没文字，也不用担心文件过大迁移失败了。

请问「文件过大迁移失败」是什么意思？

图片放到 md 里面是什么意思？
- 图片和文件同一目录？
