### ISSUE TITLE
中文乱码问题

### ISSUE THREAD

**Issue by vantexi** [DeppWang/youdaonote-pull#6]
自定义要导出的文件目录，程序读取信息需要设置成“utf-8”,否则会出现中文乱码匹配不上文件夹名
` with open('config.json', 'r',encoding="utf-8")
`
其他读写文件的地方,建议都改成utf-8

**Comment by DeppWang** [comment]
感谢指出，好的

**Comment by DeppWang** [comment]
已改为使用字节写入和读取。
