### ISSUE TITLE
错误提示：'有道云笔记修改了接口地址，此脚本暂时不能使用！请提 issue'

### ISSUE THREAD

**Issue by lvhoo** [DeppWang/youdaonote-pull#60]
转换为 Markdown 失败！请检查文件！
错误提示：child index out of range
错误提示：'有道云笔记修改了接口地址，此脚本暂时不能使用！请提 issue'
已终止执行

**Comment by DeppWang** [comment]
报这个错误时，一个文件也没导出成功吗

**Comment by lvhoo** [comment]
第一次成功运行起来后，导出了几个文章。然后就弹出这个提示了。再次运行就直接提示。
后面按你博客找接口的方式，改了接口，就运行成功了。
但是很多旧文章，里面的图片、附件都导出不成功，只有标题和内部的文字。

**Comment by DeppWang** [comment]
旧文章导出来是 html 格式吗？
