### ISSUE TITLE
markdown 格式无法保留原来笔记的颜色和格式

### ISSUE THREAD

**Issue by musicpiano** [DeppWang/youdaonote-pull#61]
您好，

感谢您的程序，我成功的下载了有道所有的笔记。不过因为我原来的笔记有很多不同的颜色和格式，下载后这些格式在markdown里面无法显示出来。请问有没有可能把所有笔记下载成其他格式呢？

谢谢

**Comment by DeppWang** [comment]
颜色和格式程序暂时还不支持转换，程序也不提供将笔记保存为其他格式的功能
