### ISSUE TITLE
有道云新版笔记导出不了

### ISSUE THREAD

**Issue by Auroar** [DeppWang/youdaonote-pull#65]
导出后显示客户端版本过低
![image](https://user-images.githubusercontent.com/55086404/161677043-69b79e00-db00-41f3-9a38-c66228022ce0.png)
![image](https://user-images.githubusercontent.com/55086404/161677170-bc0715ca-bcd4-4d81-a454-c6da158a9f65.png)

**Comment by DeppWang** [comment]
原因可能是你编辑器版本过低导致的，建议在网页或者最新客户端重新打开一下笔记，再尝试下载，看是否可行

**Comment by Auroar** [comment]
> 原因可能是你编辑器版本过低导致的，建议在网页或者最新客户端重新打开一下笔记，再尝试下载，看是否可行

网页端打开笔记是没有问题的，删除了文件后重新执行了一下还是不行。

**Comment by DeppWang** [comment]
你把你出错的这篇笔记用网页打开一下，不要删除，重新下载，看是否可以下载成功

**Comment by DeppWang** [comment]
我说的下载指重新运行脚本

**Comment by Auroar** [comment]
> 我说的下载指重新运行脚本

刚刚重新下载了一遍，下载完成后重新打开笔记更新了一下修改时间，在下载后还是提示需要更新新版笔记

**Comment by DeppWang** [comment]
尝试在网页版上新建一个目录，再新建一篇测试笔记，脚本指定目录下载一下，看是否正常

**Comment by Auroar** [comment]
> 尝试在网页版上新建一个目录，再新建一篇测试笔记，脚本指定目录下载一下，看是否正常
刚刚尝试了一下，全部使用网页新建目录和新建笔记，下载后还是提示需要新版笔记。

**Comment by DeppWang** [comment]
这个错误我没能复现，你尝试替换一下 pull.py 中 `User-Agent`，再尝试下载，看是否可以解决这个问题。

```
'User-Agent': 'Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/63.0.3239.84 Safari/537.36',
``` 
替换为 
```
'User-Agent': 'Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/99.0.4844.51 Safari/537.36',
```

**Comment by DeppWang** [comment]
更新了脚本，可以再试试

**Comment by TenderLover** [comment]
获取文件的参数要调整，我没看哪个参数有影响，把能拷贝过来的都加上就可以了，其中_appuser这些我都是直接写死了。
FILE_URL = 'https://note.youdao.com/yws/api/personal/sync?method=download&_system=windows&_systemVersion=&_screenWidth=1536&_screenHeight=864&_appName=ynote&_appuser=0123456789abcdeffedcba9876543210&_vendor=official-website&_launch=11&_deviceId=0123456789abcdef&_platform=web&_cityCode=330100&sev=j1&keyfrom=web&cstk=%s';

**Comment by TenderLover** [comment]
@DeppWang @Auroar 亲测可用

**Comment by Auroar** [comment]
@TenderLover @DeppWang 我刚吧更新后的下载了测试了下，还是不行，这个是我的操作视频链接
https://www.bilibili.com/video/BV1X44y1V71k?spm_id_from=333.999.0.0

**Comment by DeppWang** [comment]
> 获取文件的参数要调整，我没看哪个参数有影响，把能拷贝过来的都加上就可以了，其中_appuser这些我都是直接写死了。 FILE_URL = 'https://note.youdao.com/yws/api/personal/sync?method=download&_system=windows&_systemVersion=&_screenWidth=1536&_screenHeight=864&_appName=ynote&_appuser=0123456789abcdeffedcba9876543210&_vendor=official-website&_launch=11&_deviceId=0123456789abcdef&_platform=web&_cityCode=330100&sev=j1&keyfrom=web&cstk=%s';

@Auroar 尝试按这样修改过 FILE_URL 吗？按这种方式修改一下试试
