### ISSUE TITLE
有道云笔记导出md，打开是乱码

### ISSUE THREAD

**Issue by ausle** [DeppWang/youdaonote-pull#69]
运行pull.py时，提示 ‘utf-8’ codec decode byte的错误。
然后我就改了pull.py文件，把decode('utf-8')改成了decode('utf-8','ignore')。
然后就没有错误，成功转成了md。
可md打开全是乱码。并且本地的路径下没有图片。请问开发者，我哪个步骤有问题。

**Comment by roland1003053305** [comment]
![image](https://user-images.githubusercontent.com/104717439/166269055-8056fc9e-5736-46f2-9286-762b87b8e665.png)
