### ISSUE TITLE
没有账号和密码，这个需要怎么弄？

### ISSUE THREAD

**Issue by AnsonZnl** [DeppWang/youdaonote-pull#7]
我的有道云笔记都是使用微信登录的，没有账号和密码，这个需要怎么弄？

**Comment by DeppWang** [comment]
应该可以在网页版有道云笔记的「账号设置」里面绑定，你看看吧

**Comment by DeppWang** [comment]
有道云笔记默认使用的是网易邮箱账号密码，应该默认绑定了。即使你使用微信登录，应该也可以用网易邮箱账号密码登录。

**Comment by AnsonZnl** [comment]
非常感谢您的回复，还是不行，但是我想到一个折中的办法。
1. 我先导出现有账号的笔记（.ynt）
2. 我使用新的邮箱注册了一个有道云笔记
3. 在新账号里导入我现有的笔记

然后使用新的账号，使用`python pull.py`却只下载了3个日记（原本有几百个日记的），这是怎么回事啊？

**Comment by DeppWang** [comment]
你贴一下运行截图

**Comment by AnsonZnl** [comment]
> 你贴一下运行截图

以下是运行截图：
![image.png](https://upload-images.jianshu.io/upload_images/7072486-36a8eab666a86ce7.png?imageMogr2/auto-orient/strip%7CimageView2/2/w/1240)

**Comment by DeppWang** [comment]
应该是笔记文件名多了个？，那删除再试试。如果是这个原因，后面我改改代码

**Comment by AnsonZnl** [comment]
是的，有个文件名带有`?`，删除了就好了，感谢大佬！！给你个赞~~

**Comment by AnsonZnl** [comment]
因为我的文件较多，经过我的测试，当文件名中含有`? . _ `和空格时会报错

**Comment by DeppWang** [comment]
文件名中含有 `? . _` 和空格的是收藏的网址吗？一般自己新建笔记都不能有特殊符号

**Comment by AnsonZnl** [comment]
对，两种情况：
1. 在微信或者浏览器上使用有道云笔记的插件保存文章/网页在有道云笔记里
2. 我自己新建的笔记有一写标题随手会加个空号或者.

**Comment by DeppWang** [comment]
只要标题没有斜杠 `/`，含有 `? . _ 和空格`下载是不应该有问题的。但你电脑确实存在这个问题，应该跟电脑有关。我找找原因

**Comment by DeppWang** [comment]
Windows 默认装有 `PowerShell` ，你用 `PowerShell` 试试

**Comment by DeppWang** [comment]
你前面说你将笔记导出为 .ynt，你是会员？我没发现可以导出 .ynt 的选项呀

**Comment by AnsonZnl** [comment]
Windows桌面可以
![Windows桌面](https://upload-images.jianshu.io/upload_images/7072486-b4002e7b0cf71383.png?imageMogr2/auto-orient/strip%7CimageView2/2/w/1240)

**Comment by DeppWang** [comment]
你这个客户端是最新版本吗？

**Comment by AnsonZnl** [comment]
客户端一直都可以，新版本也可以的。

**Comment by DeppWang** [comment]
你是有道云笔记的会员？

**Comment by AnsonZnl** [comment]
不是啊，不用会员也能导出的。

> 你是有道云笔记的会员？

**Comment by DeppWang** [comment]
了解了，感谢。脚本你还是运行失败？建议使用 PowerShell
