### ISSUE TITLE
可以导出为html吗？

### ISSUE THREAD

**Issue by roland1003053305** [DeppWang/youdaonote-pull#70]
你好
可以导出为html吗？
我这边是想从有道云笔记搬迁到wolai，
经过测试，
如果是html
导入wolai后**还原度**更高。

在贴吧看到一个帖子，哈哈哈
![image](https://user-images.githubusercontent.com/104717439/166326547-5628bf93-d706-406d-8577-72293fb77a0a.png)

**Comment by DeppWang** [comment]
你好，无法导出为 html。
