### ISSUE TITLE
05/03使用，会报'utf-8' codec can't decode byte 0xb4 in position 1: invalid start byte错误

### ISSUE THREAD

**Issue by zzy8911** [DeppWang/youdaonote-pull#71]
执行报错：
此 note 笔记应该为 17 年以前新建，格式为 html，将转换为 Markdown...
「/home/uzhoz144/work/code/github/youdaonote-pull/youdaonote/来自印象笔记/linux命令.note」转换为 Markdown 失败！请检查文件！
错误提示：'utf-8' codec can't decode byte 0xb4 in position 1: invalid start byte

打开对应.note是二进制文件，不管是ubuntu还是win10都是这个问题。

**Comment by CodeYiShu** [comment]
我也是

**Comment by Steveneve** [comment]
我也是同样的问题

**Comment by 583175694** [comment]
出现异常报错是由于设置了decode()方法的第二个参数errors为严格（strict）形式造成的，因为默认就是这个参数
将
`decode("utf8")`
更改为ignore等即可。
`.decode("utf8","ignore")`

**Comment by fs714** [comment]
我也是

**Comment by DeppWang** [comment]
因为有道云笔记将 note 类型的 Content-Encoding 改为了 `br` 格式，[以降低文件内容大小](https://tech.oyorooms.com/how-brotli-compression-gave-us-37-latency-improvement-14d41e50fee4)，`br` 默认不解码，所以需要安装 [brotli](https://github.com/google/brotli)「解码」。
```
pip install brotli
or
pip3 install brotli
```
安装后再尝试

**Comment by CodeYiShu** [comment]
> 



> 因为有道云笔记将 note 类型的 Content-Encoding 改为了 `br` 格式，[以降低文件内容大小](https://tech.oyorooms.com/how-brotli-compression-gave-us-37-latency-improvement-14d41e50fee4)，`br` 默认不解码，所以需要安装 [brotli](https://github.com/google/brotli)「解码」。
> 
> ```
> pip install brotli
> or
> pip3 install brotli
> ```
> 
> 安装后再尝试
终于等到您了老哥！非常感谢！可以了

**Comment by Steveneve** [comment]
> 因为有道云笔记将 note 类型的 Content-Encoding 改为了 `br` 格式，[以降低文件内容大小](https://tech.oyorooms.com/how-brotli-compression-gave-us-37-latency-improvement-14d41e50fee4)，`br` 默认不解码，所以需要安装 [brotli](https://github.com/google/brotli)「解码」。
> 
> ```
> pip install brotli
> or
> pip3 install brotli
> ```
> 
> 安装后再尝试

成功了，多谢！
