### ISSUE TITLE
导出的笔记都为note 无法打开

### ISSUE THREAD

**Issue by menfutong** [DeppWang/youdaonote-pull#72]

**Comment by DeppWang** [comment]
因为有道云笔记将 note 类型的 Content-Encoding 改为了 `br` 格式，[以降低文件内容大小](https://tech.oyorooms.com/how-brotli-compression-gave-us-37-latency-improvement-14d41e50fee4)，`br` 默认不解码，所以需要安装 [brotli](https://github.com/google/brotli)「解码」。
```
pip install brotli
or
pip3 install brotli
```
安装后再尝试
