### ISSUE TITLE
此note为17年之前所创创建、无法进行转换怎么把

### ISSUE THREAD

**Issue by NepoleonASM** [DeppWang/youdaonote-pull#73]
跪求解决办法、我明明刚创建的

**Comment by DeppWang** [comment]
因为有道云笔记将 note 类型的 Content-Encoding 改为了 `br` 格式，[以降低文件内容大小](https://tech.oyorooms.com/how-brotli-compression-gave-us-37-latency-improvement-14d41e50fee4)，`br` 默认不解码，所以需要安装 [brotli](https://github.com/google/brotli)「解码」。
```
pip install brotli
or
pip3 install brotli
```
安装后再尝试

**Comment by NepoleonASM** [comment]
thank you，The problem is solved
