### ISSUE TITLE
note」转换为 Markdown 失败！请检查文件！ 错误提示：'level'

### ISSUE THREAD

**Issue by NepoleonASM** [DeppWang/youdaonote-pull#74]
大佬这种问题怎么解决的。麻烦求告知

**Comment by DeppWang** [comment]
请贴一个完整的提示

**Comment by NepoleonASM** [comment]
「/Users/Desktop/111/youdaonote/20220511课堂笔记.note」转换为 Markdown 失败！请检查文件！
错误提示：'level'

**Comment by NepoleonASM** [comment]
<img width="827" alt="image" src="https://user-images.githubusercontent.com/37949632/168015841-4cf83fc8-c688-4c40-8b72-bfe80992cc73.png">

**Comment by DeppWang** [comment]
你再试试

**Comment by NepoleonASM** [comment]
@DeppWang 还是一样的问题、其他的文件都可以正确转换

**Comment by DeppWang** [comment]
拉取最新代码了吗
