### ISSUE TITLE
 'gbk' codec can't decode byte 0xb0 in position 109: illegal multibyte sequence

### ISSUE THREAD

**Issue by CodeYiShu** [DeppWang/youdaonote-pull#75]
拉取了最新版本代码，执行python pull.py之后报异常；而且已经确认过config.json、cookie.json和pull.py的编码都是utf8
![图片](https://user-images.githubusercontent.com/50818497/168940059-e9c7ba25-fd8e-4c52-bfed-dfbc0b01d47f.png)

**Comment by DeppWang** [comment]
> requirements.txt 文件设置为# _*_ coding:utf-8 _*_ ![image](https://user-images.githubusercontent.com/84823804/168984823-a527db1c-86b4-4bed-963e-bbc1ab785f64.png) ![image](https://user-images.githubusercontent.com/84823804/168984876-8d38e527-e62f-4118-9b0d-e6d3c8ef3059.png)

这个报错和 `requirements.txt` 没有关系

**Comment by CodeYiShu** [comment]
> > 拉取了最新版本代码，执行python pull.py之后报异常；而且已经确认过config.json、cookie.json和pull.py的编码都是utf8 ![图片](https://user-images.githubusercontent.com/50818497/168940059-e9c7ba25-fd8e-4c52-bfed-dfbc0b01d47f.png)
> 
> 应该还是格式的问题，我优化了一下代码，你拉最新代码再试试。



> > requirements.txt 文件设置为# _*_ coding:utf-8 _*_ ![image](https://user-images.githubusercontent.com/84823804/168984823-a527db1c-86b4-4bed-963e-bbc1ab785f64.png) ![image](https://user-images.githubusercontent.com/84823804/168984876-8d38e527-e62f-4118-9b0d-e6d3c8ef3059.png)
> 
> 这个报错和 `requirements.txt` 没有关系

有用，解决了大佬！谢谢
