### ISSUE TITLE
新增失败！请检查文件，错误提示

### ISSUE THREAD

**Issue by puchihhh** [DeppWang/youdaonote-pull#76]
用了最新代码，全部提示‘新增失败！请检查文件，错误提示’。最后导出的文件格式都是note后缀
![Snipaste_2022-05-20_10-49-35](https://user-images.githubusercontent.com/55620106/169439364-bcac558a-cd88-4d0f-b9ff-8ceee723d3c1.png)

**Comment by puchihhh** [comment]
才发现关闭issue里有过这类问题。。已经解决了，感谢大佬！！

**Comment by visiLi** [comment]
https://github.com/DeppWang/youdaonote-pull/issues/73
