### ISSUE TITLE
执行脚本抛KeyError fileEntry

### ISSUE THREAD

**Issue by CodeYiShu** [DeppWang/youdaonote-pull#78]
![图片](https://user-images.githubusercontent.com/50818497/170185071-c582e355-eaff-4a7c-8397-98ff28803bb4.png)

**Comment by DeppWang** [comment]
请确认 cookies 是否正确

**Comment by CodeYiShu** [comment]
> 请确认 cookies 是否正确

是的 cookie错了 不好意思大佬
