### ISSUE TITLE
有道云笔记批量导出出现报错：'utf-8' codec can't decode byte 0xb4 in position 1: invalid start byte

### ISSUE THREAD

**Issue by hufanqie** [DeppWang/youdaonote-pull#80]
执行报错：
此 note 笔记应该为 17 年以前新建，格式为 html，将转换为 Markdown...
「/home/uzhoz144/work/code/github/youdaonote-pull/youdaonote/来自印象笔记/linux命令.note」转换为 Markdown 失败！请检查文件！
错误提示：'utf-8' codec can't decode byte 0xb4 in position 1: invalid start byte

请问一下这个要怎么处理呀？

**Comment by DeppWang** [comment]
你是什么系统？尝试 pull 最新代码后重试
