### ISSUE TITLE
note 笔记转换 MarkDown 失败，将跳过

### ISSUE THREAD

**Issue by crh19970307** [DeppWang/youdaonote-pull#85]
note 笔记转换 MarkDown 失败，将跳过
好像有的笔记转换失败，是不是有道云笔记的格式有变化？

**Comment by DeppWang** [comment]
贴一下错误提示与错误笔记吧

**Comment by 0kangkang0** [comment]
我也遇到了同样的问题
提示是这样的
note 笔记转换 MarkDown 失败，将跳过<class 'Exception'>
新增「D:/笔记/youdaonote-pull/youdaonote/JavaWeb.note」失败！请检查文件！错误提示：[Errno 2] No such file or directory: 'D:/笔记/youdaonote-pull/youdaonote/JavaWeb.md'
笔记是这篇
https://note.youdao.com/s/CQu9lBuq

**Comment by 0kangkang0** [comment]
> 我也遇到了同样的问题 提示是这样的 note 笔记转换 MarkDown 失败，将跳过<class 'Exception'> 新增「D:/笔记/youdaonote-pull/youdaonote/JavaWeb.note」失败！请检查文件！错误提示：[Errno 2] No such file or directory: 'D:/笔记/youdaonote-pull/youdaonote/JavaWeb.md' 笔记是这篇 https://note.youdao.com/s/CQu9lBuq

解决了，参考https://github.com/DeppWang/youdaonote-pull/issues/81
我在笔记中有含有空白的表格
