### ISSUE TITLE
找不到fileEntry参数，是不是有道关闭了接口？

### ISSUE THREAD

**Issue by SeanSoong** [DeppWang/youdaonote-pull#86]
现在root_dir_info是这样的：
 {'canTryAgain': False, 'scope': 'SECURITY', 'error': '207', 'message': 'Message[AUTHENTICATION_FAILURE]: User token must be authenticated.', 'objectUser': None}
是不是有道关闭了接口啊？看样子需要提供用户信息，想上官网查看api，必须要通过申请，申请要填app域名

**Comment by DeppWang** [comment]
我测试没问题，请使用 cookies 登录，请确认 cookies 配置正确
