### ISSUE TITLE
Error message missing 错误提示缺失

### ISSUE THREAD

**Issue by holmebin** [DeppWang/youdaonote-pull#88]
pull.py的560行，捕捉了异常，但是format未打印
`        try:
            self._pull_file(file_id, original_file_path, local_file_path, is_note, youdao_file_suffix)
            print('{}「{}」{}'.format(file_action.value, local_file_path, tip))
        except Exception as error:
            print('{}「{}」失败！请检查文件！错误提示：'.format(file_action.value, original_file_path, format(error))) 
`
改为
`
print('{}「{}」失败！请检查文件！错误提示：{}'.format(file_action.value, original_file_path, format(error))) 
`
或
`
print('{}「{}」失败！请检查文件！错误提示：'.format(file_action.value, original_file_path)) 
 traceback.print_exc()
`

**Comment by DeppWang** [comment]
感谢建议

**Comment by holmebin** [comment]
因为工作的关系，曾面对无数好友呼叫不能回应，最痛苦的事莫过于此！  如果给我一次机会 ，我要说一句话：不是我不理你，只是时间难以抗拒！！  如果一定要给这句话加个期限，我希望是：再等一会儿！！！
