### ISSUE TITLE
新增失败

### ISSUE THREAD

**Issue by lmzds** [DeppWang/youdaonote-pull#89]
![image](https://user-images.githubusercontent.com/54607424/199218273-11db5e86-85db-4fba-9756-31119000841e.png)
这要怎么解决

**Comment by DeppWang** [comment]
是否使用了 SMMS 图床，如果使用可尝试关闭，看看是否可以解决

**Comment by DeppWang** [comment]
请拉一下最新代码，最新代码修复了错误提示不打印的问题，如果还有问题，再贴一下错误截图

**Comment by lmzds** [comment]
> 请拉一下最新代码，最新代码修复了错误提示不打印的问题，如果还有问题，再贴一下错误截图

两个文件生成了，但是图片没有转成功，还是有道云的链接
![image](https://user-images.githubusercontent.com/54607424/199421309-184e76f8-786e-4674-b2de-a8cc6a23446b.png)

**Comment by lmzds** [comment]
> 是否使用了 SMMS 图床，如果使用可尝试关闭，看看是否可以解决

图床的话没有使用，我是保存本地的。其他正常和报错的两个文件
![image](https://user-images.githubusercontent.com/54607424/199421898-1e388823-16b0-4f1f-bccf-2706561a28a9.png)
![image](https://user-images.githubusercontent.com/54607424/199421994-96beb72e-1d49-4aeb-bcc3-693b2c2a495c.png)

**Comment by lmzds** [comment]
https://note.youdao.com/s/ApqrFUG0

**Comment by lmzds** [comment]
https://note.youdao.com/s/ApqrFUG0
https://note.youdao.com/s/OPwJEyu
有问题的两篇文章

**Comment by DeppWang** [comment]
好的，我晚上看一下

**Comment by DeppWang** [comment]
已修复此问题，请拉取最新代码
