### ISSUE TITLE
not enough arguments for format string

### ISSUE THREAD

**Issue by nayutalin** [DeppWang/youdaonote-pull#9]
如题，导出某些文件时抛错：
> not enough arguments for format string
已终止执行

似乎是转换有道云图床的图片到本地的时候抛的。

**Comment by DeppWang** [comment]
是最新代码么？

**Comment by nayutalin** [comment]
应该是get_new_down_or_upload_url返回的外部url含有特殊字符导致后面格式化失败，比如这个：
https://www.zhihu.com/equation?tex=+k+%3D+%5Cleft%5B%5Cfrac%7Blog%28-z_%7Bvs%7D+%2F+near%29%7D%7Blog%281+%2B+%5Cfrac%7B2tan%5Ctheta%7D%7BS_y%7D%29%7D+%5Cright%5D+

**Comment by DeppWang** [comment]
感谢指出，此问题已修复
