### ISSUE TITLE
导出本地无法使用相对路径，挪位置后，里面的图片都显示不了了

### ISSUE THREAD

**Issue by M-Kepler** [DeppWang/youdaonote-pull#90]

**Comment by M-Kepler** [comment]
DONE: https://github.com/DeppWang/youdaonote-pull/commit/da684c03a6bba39c6e8c299873cbc176b8302594

**Comment by zhixiongzh** [comment]
非常好用，建议拉一个PR

**Comment by DeppWang** [comment]
已新增相对路径下载选项 #92
