### ISSUE TITLE
markdown文档里面图像路径问题

### ISSUE THREAD

**Issue by Trings** [DeppWang/youdaonote-pull#91]
你好，能否增加一个选项，让导出的文档能使用相对路径来引用图片呢。这样本地迁移或者分享给他人的时候查看更方便一点。

**Comment by M-Kepler** [comment]
https://github.com/DeppWang/youdaonote-pull/issues/90

**Comment by HongYan789** [comment]
可以看看#92 ，已合并到主流程中
