### ISSUE TITLE
运行时新增失败跳过，错误提示：[Errno 2] No such file or directory: 

### ISSUE THREAD

**Issue by ReyXRey** [DeppWang/youdaonote-pull#94]
![image](https://user-images.githubusercontent.com/28730296/205490465-87f81efa-3791-4683-80eb-4bc53c3cf465.png)

**Comment by Momohanfeng** [comment]
> ![image](https://user-images.githubusercontent.com/28730296/205490465-87f81efa-3791-4683-80eb-4bc53c3cf465.png)

应该是文章标题中含有在windows上无法创建为文件名的字符。比如我遇到的是C++，在pull下来的时候++被解码成windows不能认识的字符，所以显示这个错误。我的做法是在网页端把对应笔记重命名。因为在网页版上我的这个标题也被解码错误了，希望对你有帮助
