### ISSUE TITLE
安装依赖包时的解码问题

### ISSUE THREAD

**Issue by snake-git** [DeppWang/youdaonote-pull#96]
按照教程在安装 pip install -r requirements.txt 时出现以下解码问题：
 File "c:\users\****\appdata\local\programs\python\python38\lib\site-packages\pip\_internal\utils\encoding.py", line 34, in auto_decode
    return data.decode(
UnicodeDecodeError: 'gbk' codec can't decode byte 0xac in position 54: illegal multibyte sequence
不知如何解决？
系统： 两台台式机（一台win10 {22H}中文版，一台win7 中文专业版）。

**Comment by qhadyn** [comment]
txt文件的编码格式原因，可以把Txt文本里边的内容拷贝出来单独执行：
pip install requests==2.22.0
pip install markdownify==0.5.1
pip install Brotli==1.0.9

**Comment by snake-git** [comment]
> txt文件的编码格式原因，可以把Txt文本里边的内容拷贝出来单独执行： pip install requests==2.22.0 pip install markdownify==0.5.1 pip install Brotli==1.0.9

谢谢，回去试试看。

**Comment by LuckyCenter** [comment]
> txt文件的编码格式原因，可以把Txt文本里边的内容拷贝出来单独执行： pip install requests==2.22.0 pip install markdownify==0.5.1 pip install Brotli==1.0.9

同样遇到这个问题。这个方法，亲测有用。
