### ISSUE TITLE
2017年以前的笔记转码失败

### ISSUE THREAD

**Issue by snake-git** [DeppWang/youdaonote-pull#97]
Pull 出来的笔记，貌似2017年以前的笔记会转码失败？越是近年的笔记转码成功率越高。不知啥原因？
引用：
“此 note 笔记应该为 17 年以前新建，格式为 html，将转换为 Markdown ...
新增「/home/....../youdaonote-pull/youdaonote/编程随想网络安全/流氓的桌面软件有哪些替代品？.note」失败！请检查文件！错误提示：No module named 'markdownify'
note 笔记转换 MarkDown 失败，将跳过”

求解，谢谢！

**Comment by DeppWang** [comment]
没有安装 markdownify 依赖包，先安装 markdownify 依赖包后再尝试
```shell
pip install markdownify
```
2017 前的笔记应该是 html 格式，没有 markdownify 包时，无法转换

**Comment by snake-git** [comment]
谢谢大佬的回复，回去试试。照说按照你的教程完成了requirements那一步，里面应该包含了这个模块， 前面的笔记都顺利转换成功。有道太坑人了，幸好有大佬的脚本，再次感谢！

**Comment by snake-git** [comment]
报告大佬，重新安装模块，显示已成存在了。但是转码仍然出现同样错误。 系统为Debian9。

引用：
root@Proxypool:/home/allen/youdaonote-pull# pip install requests==2.22.0 
Requirement already satisfied: requests==2.22.0 in /usr/local/lib/python2.7/dist-packages (2.22.0)
Requirement already satisfied: idna<2.9,>=2.5 in /usr/local/lib/python2.7/dist-packages (from requests==2.22.0) (2.8)
Requirement already satisfied: chardet<3.1.0,>=3.0.2 in /usr/local/lib/python2.7/dist-packages (from requests==2.22.0) (3.0.4)
Requirement already satisfied: certifi>=2017.4.17 in /usr/local/lib/python2.7/dist-packages (from requests==2.22.0) (2021.10.8)
Requirement already satisfied: urllib3!=1.25.0,!=1.25.1,<1.26,>=1.21.1 in /usr/local/lib/python2.7/dist-packages (from requests==2.22.0) (1.25.11)
root@Proxypool:/home/allen/youdaonote-pull# pip install markdownify==0.5.1 
Requirement already satisfied: markdownify==0.5.1 in /usr/local/lib/python2.7/dist-packages (0.5.1)
Requirement already satisfied: beautifulsoup4 in /usr/local/lib/python2.7/dist-packages (from markdownify==0.5.1) (4.9.3)
Requirement already satisfied: six in /usr/lib/python2.7/dist-packages (from markdownify==0.5.1) (1.12.0)
Requirement already satisfied: soupsieve<2.0,>1.2; python_version < "3.0" in /usr/local/lib/python2.7/dist-packages (from beautifulsoup4->markdownify==0.5.1) (1.9.6)
Requirement already satisfied: backports.functools-lru-cache; python_version < "3" in /usr/local/lib/python2.7/dist-packages (from soupsieve<2.0,>1.2; python_version < "3.0"->beautifulsoup4->markdownify==0.5.1) (1.6.4)
root@Proxypool:/home/allen/youdaonote-pull# pip install Brotli==1.0.9
Requirement already satisfied: Brotli==1.0.9 in /usr/local/lib/python2.7/dist-packages (1.0.9)

此 note 笔记应该为 17 年以前新建，格式为 html，将转换为 Markdown ...
新增「/home/allen/youdaonote-pull/youdaonote/编程随想网络安全/流氓的桌面软件有哪些替代品？.note」失败！请检查文件！错误提示：No module named 'markdownify'
note 笔记转换 MarkDown 失败，将跳过”

**Comment by DeppWang** [comment]
用 Python3

**Comment by snake-git** [comment]
> 用 Python3

Pull 的命令是python3:

root@Proxypool:/home/####/youdaonote-pull# python3 pull.py
本次使用 Cookies 登录
正在 pull，请稍后 ...
此 note 笔记应该为 17 年以前新建，格式为 html，将转换为 Markdown ...
新增「/home/allen/youdaonote-pull/youdaonote/Digital World/Linux/Linux目录结构.note」失败！请检查文件！错误提示：No module named 'markdownify'
此 note 笔记应该为 17 年以前新建，格式为 html，将转换为 Markdown ...
新增「/home/allen/youdaonote-pull/youdaonote/Digital World/Linux/CentOS下找不到eth0设备的解决方法.note」失败！请检查文件！错误提示：No module named 'markdownify'
此 note 笔记应该为 17 年以前新建，格式为 html，将转换为 Markdown ...

**Comment by DeppWang** [comment]
markdownify 没有安装，用 pip3 安装
