### ISSUE TITLE
图片成功上传到图床，但md中的链接为g

### ISSUE THREAD

**Issue by iErics** [DeppWang/youdaonote-pull#98]
如图：
![截屏2023-02-19 20 07 54](https://user-images.githubusercontent.com/42070668/219947203-abb1e7de-7f68-4b36-aba7-f464bab57155.png)

**Comment by isofun** [comment]
俺也一样

**Comment by iamtt** [comment]
俺也一样

**Comment by DeppWang** [comment]
此问题已修复
